-- made with brmodelo :>


CREATE TABLE USUARIO (
    email VARCHAR(256) PRIMARY KEY,
    nome VARCHAR(256) NOT NULL,
    senha VARCHAR(256) NOT NULL,
    idImUsuario BIGINT,
    CONSTRAINT FK_USUARIO FOREIGN KEY (idImUsuario) REFERENCES IMAGEMUSUARIO (idImUsuario) ON DELETE RESTRICT;
);

CREATE TABLE REPUBLICA (
    idRepublica BIGINT PRIMARY KEY,
    nome VARCHAR(256),
    cep VARCHAR(256),
    complemento VARCHAR(256),
    numero INT,
    email VARCHAR(256),
    CONSTRAINT FK_REPUBLICA FOREIGN KEY (email) REFERENCES USUARIO (email) ON DELETE RESTRICT;
);

CREATE TABLE ALUGUEL (
    idAluguel BIGINT PRIMARY KEY,
    FK_USUARIO_email VARCHAR(256),
    FK_REPUBLICA_idRepublica BIGINT
);

CREATE TABLE IMAGEMREPUBLICA (
    idImRepublica BIGINT PRIMARY KEY,
    caminhoImRepublica VARCHAR(256),
    FK_REPUBLICA_idRepublica BIGINT
);

CREATE TABLE IMAGEMUSUARIO (
    idImUsuario BIGINT PRIMARY KEY,
    caminhoImUsuario VARCHAR(256)
);
 
ALTER TABLE REPUBLICA ADD 
 
ALTER TABLE ALUGUEL ADD CONSTRAINT FK_ALUGUEL_2
    FOREIGN KEY (FK_USUARIO_email)
    REFERENCES USUARIO (email)
    ON DELETE RESTRICT;
 
ALTER TABLE ALUGUEL ADD CONSTRAINT FK_ALUGUEL_3
    FOREIGN KEY (FK_REPUBLICA_idRepublica)
    REFERENCES REPUBLICA (idRepublica)
    ON DELETE RESTRICT;
 
ALTER TABLE IMAGEMREPUBLICA ADD CONSTRAINT FK_IMAGEMREPUBLICA_2
    FOREIGN KEY (FK_REPUBLICA_idRepublica)
    REFERENCES REPUBLICA (idRepublica)
    ON DELETE RESTRICT;