name: Continuos Integration
on: pull_request

jobs:
  continous-integration:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: use Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: 21.x
    - name: run, install and test
      run: |
        npm install
        npm run build
        npm run test
